name: offline_accessible_retrieval
description: Offline accessible multimodal local content retrieval system by Celine Song.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.6.1
  crypto: ^3.0.3
  file_picker: ^8.1.2
  http: ^1.2.2
  path: ^1.9.0
  path_provider: ^2.1.4
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tokenizer/vocab.txt
